if(WITH_OPENCV)
  find_package(OpenCV QUIET COMPONENTS core cudaarithm)
  if(OpenCV_FOUND)
    add_definitions(-DHAVE_OPENCV)
    include_directories(${OpenCV_INCLUDE_DIRS})
    if(WIN32)
        set(bin_dirs_ "${BIN_DIRS};OpenCV")
        list(REMOVE_DUPLICATES bin_dirs_)
        set(BIN_DIRS "${bin_dirs_}" CACHE STRING "" FORCE)
        list(REMOVE_DUPLICATES BIN_DIRS)
        get_target_property(dll_file_path_ opencv_core IMPORTED_LOCATION_RELEASE)
        get_filename_component(dll_path ${dll_file_path_} DIRECTORY)
        set(OpenCV_BIN_DIR ${dll_path} CACHE PATH "" FORCE)
        set(OpenCV_BIN_DIR_OPT ${dll_path} CACHE PATH "" FORCE)
        list(APPEND PROJECT_BIN_DIRS_DEBUG ${dll_path})
        list(APPEND PROJECT_BIN_DIRS_RELEASE ${dll_path})
        list(APPEND PROJECT_BIN_DIRS_RELWITHDEBINFO ${dll_path})
    endif()
  endif()
endif(WITH_OPENCV)
