if(WITH_PYTHON)
    find_package(PythonLibs QUIET)
    find_package(PythonInterp QUIET)
    if(PythonLibs_FOUND AND PythonInterp_FOUND)
        message("Found python ${python_version}")
        if(WIN32)
            find_package(Boost QUIET COMPONENTS python python3 python2)
            if(Boost_PYTHON_FOUND)
                set(HAVE_PYTHON ON)
                message("Building python bindings")
                list(APPEND link_libs "${Boost_PYTHON_LIBRARY_RELEASE};${PYTHON_LIBRARY}")
                get_filename_component(_python_lib_dirs "${PYTHON_LIBRARY}" DIRECTORY)
                foreach(dir ${_python_lib_dirs})
                    if(NOT ${dir} STREQUAL debug AND NOT ${dir} STREQUAL optimized)
                        link_directories(${dir})
                    endif()
                endforeach()
                include_directories(${PYTHON_INCLUDE_DIR})
                add_definitions(-DHAVE_BOOST_PYTHON)
            endif()
        else(WIN32)
            # Find the matching boost python implementation
            set(version ${PYTHONLIBS_VERSION_STRING})
            STRING( REGEX REPLACE "[^0-9]" "" boost_py_version ${version} )
            find_package(Boost 1.46 QUIET COMPONENTS "python-py${boost_py_version}")
            set(Boost_PYTHON_FOUND ${Boost_PYTHON-PY${boost_py_version}_FOUND})

            while(NOT "${version}" STREQUAL "" AND NOT Boost_PYTHON_FOUND)
                STRING( REGEX REPLACE "([0-9.]+).[0-9]+" "\\1" version ${version} )

                STRING( REGEX REPLACE "[^0-9]" "" boost_py_version ${version} )
                find_package(Boost 1.46 COMPONENTS "python-py${boost_py_version}")
                set(Boost_PYTHON_FOUND ${Boost_PYTHON-PY${boost_py_version}_FOUND})

                STRING( REGEX MATCHALL "([0-9.]+).[0-9]+" has_more_version ${version} )
                if("${has_more_version}" STREQUAL "")
                  break()
                endif()
            endwhile()

            find_package(NumPy 1.7.1)
            if(Boost_PYTHON_FOUND)
                set(HAVE_PYTHON ON)
                set(Boost_PYTHON_LIBRARY_RELEASE "${Boost_PYTHON-PY${boost_py_version}_LIBRARY_RELEASE}" CACHE PATH "" FORCE)
                set(Boost_PYTHON_LIBRARY_DEBUG "${Boost_PYTHON-PY${boost_py_version}_LIBRARY_DEBUG}" CACHE PATH "" FORCE)
            endif()

        endif(WIN32)
    endif()
endif()
