if(NOT BUILD_DEPENDENCIES)
    find_package(spdlog QUIET)
endif()
if(spdlog_FOUND)
    message(STATUS "spdlog found at: ${spdlog_DIR}")
else(spdlog_FOUND)
    ADD_SUBDIRECTORY("dependencies/spdlog")
endif(spdlog_FOUND)
